### ISSUE TITLE
TypeError: Bad argument childProcess.spawn(cmd, args, opts)

### ISSUE THREAD

**Issue by dman777** [sindresorhus/opn#19]
```javascript
var gulp = require('gulp');
var opn = require('opn');

var _open = function () {
    opn('http://sindresorhus.com', {app: 'firefox'});
}   

gulp.task('open', function () {
    _open();
});
~      
```
----------------------------------
```
torq@0.1.0 /home/one/github/torq-ui
└── opn@1.0.2 
````
------------------------------------------------
```
[12:45:55] Starting 'open'...
[12:45:55] 'open' errored after 1.47 ms
[12:45:55] TypeError: Bad argument
  at ChildProcess.spawn (child_process.js:936:24)
  at Object.exports.spawn (child_process.js:736:9)
  at module.exports (/home/one/github/torq-ui/node_modules/opn/index.js:58:24)
  at _open (/home/one/github/torq-ui/gulp/tasks/open.js:5:5)
  at Gulp.<anonymous> (/home/one/github/torq-ui/gulp/tasks/open.js:9:5)
  at module.exports (/home/one/github/torq-ui/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
  at Gulp.Orchestrator._runTask (/home/one/github/torq-ui/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
  at Gulp.Orchestrator._runStep (/home/one/github/torq-ui/node_modules/gulp/node_modules/orchestrator/index.js:214:10)
  at Gulp.Orchestrator.start (/home/one/github/torq-ui/node_modules/gulp/node_modules/orchestrator/index.js:134:8)
  at /usr/lib64/node_modules/gulp/bin/gulp.js:129:20
  at process._tickCallback (node.js:419:13)
  at Function.Module.runMain (module.js:499:11)
  at startup (node.js:119:16)
  at node.js:906:3
````

**Comment by sindresorhus** [comment]
You're on a old version of `opn`. Upgrade.
