### ISSUE TITLE
Incognito Not Working

### ISSUE THREAD

**Issue by brianantonelli** [sindresorhus/opn#41]
Following your example for spawning an incognito session in Chrome doesn't appear to work anymore. 

```
opn('http://sindresorhus.com', {app: ['google chrome', '--incognito']});
```

The above command, from your readme, opens the window in Chrome, but not in incognito mode.

OSX: `10.12.2`
Chrome: `56.0.2924.87`

**Comment by sindresorhus** [comment]
I think it only works if you don't have Chrome already running. There's a `-n` option for `open` to force a window, but it doesn't seem to work with an URL:

```
open -n -a "Google Chrome" https://sindresorhus.com --args --incognito
```

Just opens an empty incognito window.

**Comment by rowi1de** [comment]
`open -n -a "Google Chrome" --args "https://sindresorhus.com" --incognito`
this will open incognito windows with the url

**Comment by entozoon** [comment]
For me, the fix was `chrome` rather than `'google chrome'`.

[PR here](https://github.com/sindresorhus/opn-cli/pull/9)

**Comment by brianantonelli** [comment]
@entozoon that doesnt work for me.. 

`opn('http://sindresorhus.com', {app: ['chrome', '--incognito']});`

results in:
```
    at ChildProcess.<anonymous> (/Users/monkeymojo/Dev/alks-cli/node_modules/opn/index.js:83:13)
    at Object.onceWrapper (events.js:273:13)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:961:16)
    at Socket.stream.socket.on (internal/child_process.js:380:11)
    at Socket.emit (events.js:182:13)
    at Pipe._handle.close [as _onclose] (net.js:595:12)
(node:49415) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:49415) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by entozoon** [comment]
How frustrating, it works for me in the cli version at least.

I suspect the line where it [pushes opts.app to args](https://github.com/sindresorhus/opn/blob/master/index.js#L43) isn't working correctly for an array of items as it suggests.
Does that sound likely @sindresorhus  ?

**Comment by cekvenich** [comment]
Any updates on this?

**Comment by danielo515** [comment]
I am on the same situation

**Comment by mathiasrw** [comment]
Any news on this?

**Comment by dangreenisrael** [comment]
Bump?

**Comment by mathiasrw** [comment]
> Bump?

?

**Comment by dangreenisrael** [comment]
Sorry, I meant that I also have this issue and would like to bring it back to the forefront

**Comment by jebrii** [comment]
Still seeing this issue...

FWIW `open -n -a "Google Chrome" --args --incognito "$url"` is working for me, even if Google Chrome is already open.

**Comment by jebrii** [comment]
This should be made possible by #206

**Comment by etedesco** [comment]
On Windows 10 is not working.
Is there any hope that one day it will work?

**Comment by jfromaniello** [comment]
It works for me if I switch the order of the arguments, ie I push the target (the url) to the very last arg.

As an example:
```
#this works:
» open --new -a "Google Chrome" --args --incognito "https://en.wikipedia.org/wiki/Main_Page"

# this is what open does in MacOS and does not work:
» open --new -a "Google Chrome" "https://en.wikipedia.org/wiki/Main_Page" --args --incognito
```
