### ISSUE TITLE
spawn EACCES: Error: spawn EACCES

### ISSUE THREAD

**Issue by shanalikhan** [sindresorhus/opn#54]
I tried your library in ubuntu 
what could be the error :
```
var openurl = require('opn');
openurl("http://url.com");
```
It gives error as :
```
spawn EACCES: Error: spawn EACCES
    at exports._errnoException (util.js:1022:11)
    at ChildProcess.spawn (internal/child_process.js:313:11)
    at Object.exports.spawn (child_process.js:399:9)
    at module.exports (/home/lekhnath/.vscode/extensions/Shan.code-settings-sync-2.8.0/node_modules/opn/index.js:74:26)
    at Commons.<anonymous> (/home/lekhnath/.vscode/extensions/Shan.code-settings-sync-2.8.0/out/src/commons.js:189:25)
    at Generator.next (<anonymous>)
    at fulfilled (/home/lekhnath/.vscode/extensions/Shan.code-settings-sync-2.8.0/out/src/commons.js:4:58)
e.onUnexpectedError @ workbench.main.js:29
(anonymous) @ workbench.main.js:29
e.onUnexpectedError @ workbench.main.js:28
o @ workbench.main.js:28
t.onUnexpectedExtHostError @ workbench.main.js:28
e.handle @ workbench.main.js:28
s @ workbench.main.js:28
f @ workbench.main.js:28
_combinedTickCallback @ internal/process/next_tick.js:67
_tickCallback @ internal/process/next_tick.js:98
```

**Comment by kevva** [comment]
Does setting `chmod +x /home/lekhnath/.vscode/extensions/Shan.code-settings-sync-2.8.0/node_modules/opn/xdg-open` work? Might be related to https://github.com/sindresorhus/opn/issues/38.

**Comment by shanalikhan** [comment]
Yes it works using setting that command. Why it need to set it, library should do it.

**Comment by kevva** [comment]
This module already does that. If you try installing `opn` standalone and use, it'll work. This is an issue with the Visual Code or the extension.
