### ISSUE TITLE
Unhandled promise rejection

### ISSUE THREAD

**Issue by tstrokes** [sindresorhus/opn#60]
(node:43) Error: Exited with code 3
     at ChildProcess.cp.once.code (/frontend/node_modules/opn/index.js:82:13)
     at Object.onceWrapper (events.js:318:30)
     at emitTwo (events.js:125:13)
     at ChildProcess.emit (events.js:213:7)
     at maybeClose (internal/child_process.js:921:16)
     at Socket.stream.socket.on (internal/child_process.js:348:11)
     at emitOne (events.js:115:13)
     at Socket.emit (events.js:210:7)
     at Pipe._handle.close [as _onclose] (net.js:549:12)
     at emitWarning (internal/process/promises.js:69:15)
     at emitPendingUnhandledRejections (internal/process/promises.js:86:11)
     at runMicrotasksCallback (internal/process/next_tick.js:124:9)
     at _combinedTickCallback (internal/process/next_tick.js:131:7)
     at process._tickCallback (internal/process/next_tick.js:180:9)
(node:43) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

On newer versions of node, I receive this message.

**Comment by kevva** [comment]
Are you handling the error?
