### ISSUE TITLE
Production Issue - "You have triggered an unhandledRejection,  you may have forgotten to catch a Promise rejection:"

### ISSUE THREAD

**Issue by 2rohith2** [sindresorhus/opn#75]
Hi @sindresorhus,

When I start my `Vue Js` App, I see this error.

```
0|dev-serv | > Listening at http://localhost:3001
0|dev-serv | You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
0|dev-serv | Error: Exited with code 3
0|dev-serv |     at ChildProcess.<anonymous> (/home/ec2-user/appName/node_modules/opn/index.js:83:13)
0|dev-serv |     at ChildProcess.g (events.js:292:16)
0|dev-serv |     at emitTwo (events.js:106:13)
0|dev-serv |     at ChildProcess.emit (events.js:191:7)
0|dev-serv |     at maybeClose (internal/child_process.js:920:16)
0|dev-serv |     at Socket.<anonymous> (internal/child_process.js:351:11)
0|dev-serv |     at emitOne (events.js:96:13)
0|dev-serv |     at Socket.emit (events.js:188:7)
0|dev-serv |     at Pipe._handle.close [as _onclose] (net.js:497:12)
```

OPN Package.json
```
{
  "_args": [
    [
      {
        "raw": "opn@^4.0.2",
        "scope": null,
        "escapedName": "opn",
        "name": "opn",
        "rawSpec": "^4.0.2",
        "spec": ">=4.0.2 <5.0.0",
        "type": "range"
      },
      "myPCLocation"
    ]
  ],
  "_from": "opn@>=4.0.2 <5.0.0",
  "_id": "opn@4.0.2",
  "_inCache": true,
  "_location": "/opn",
  "_nodeVersion": "4.4.2",
  "_npmOperationalInternal": {
    "host": "packages-12-west.internal.npmjs.com",
    "tmp": "tmp/opn-4.0.2.tgz_1463477356148_0.1645404922310263"
  },
  "_npmUser": {
    "name": "sindresorhus",
    "email": "sindresorhus@gmail.com"
  },
  "_npmVersion": "3.9.0",
  "_phantomChildren": {},
  "_requested": {
    "raw": "opn@^4.0.2",
    "scope": null,
    "escapedName": "opn",
    "name": "opn",
    "rawSpec": "^4.0.2",
    "spec": ">=4.0.2 <5.0.0",
    "type": "range"
  },
  "_requiredBy": [
    "#DEV:/"
  ],
  "_resolved": "https://registry.npmjs.org/opn/-/opn-4.0.2.tgz",
  "_shasum": "7abc22e644dff63b0a96d5ab7f2790c0f01abc95",
  "_shrinkwrap": null,
  "_spec": "opn@^4.0.2",
  "_where": "myPCLocation",
  "author": {
    "name": "Sindre Sorhus",
    "email": "sindresorhus@gmail.com",
    "url": "sindresorhus.com"
  },
  "bugs": {
    "url": "https://github.com/sindresorhus/opn/issues"
  },
  "dependencies": {
    "object-assign": "^4.0.1",
    "pinkie-promise": "^2.0.0"
  },
  "description": "A better node-open. Opens stuff like websites, files, executables. Cross-platform.",
  "devDependencies": {
    "ava": "*",
    "xo": "*"
  },
  "directories": {},
  "dist": {
    "shasum": "7abc22e644dff63b0a96d5ab7f2790c0f01abc95",
    "tarball": "https://registry.npmjs.org/opn/-/opn-4.0.2.tgz"
  },
  "engines": {
    "node": ">=0.10.0"
  },
  "files": [
    "index.js",
    "xdg-open"
  ],
  "gitHead": "b56b0e981ee377d3b04c57a4e6748ad2793ada17",
  "homepage": "https://github.com/sindresorhus/opn#readme",
  "keywords": [
    "app",
    "open",
    "opn",
    "opener",
    "opens",
    "launch",
    "start",
    "xdg-open",
    "xdg",
    "default",
    "cmd",
    "browser",
    "editor",
    "executable",
    "exe",
    "url",
    "urls",
    "arguments",
    "args",
    "spawn",
    "exec",
    "child",
    "process",
    "website",
    "file"
  ],
  "license": "MIT",
  "maintainers": [
    {
      "name": "sindresorhus",
      "email": "sindresorhus@gmail.com"
    }
  ],
  "name": "opn",
  "optionalDependencies": {},
  "readme": "ERROR: No README data found!",
  "repository": {
    "type": "git",
    "url": "git+https://github.com/sindresorhus/opn.git"
  },
  "scripts": {
    "test": "xo && ava"
  },
  "version": "4.0.2"
}
```

Could someone look at it?

**Comment by SamVerschueren** [comment]
I don't think this will ever work in a front-end application. It uses `child_process` to spawn a subprocess https://github.com/sindresorhus/opn/blob/master/index.js#L76.

**Comment by 2rohith2** [comment]
@SamVerschueren Yes, I am using `Vue CLI`, but in the error, it says `OPN` didn't handle `Promise rejection` in `opn/index.js:83:13`.

Could you please look in that file?

**Comment by 2rohith2** [comment]
I know what is the issue, I am running the development server in production.
